name: portfolio
services:
  - name: web
    github:
      repo: jtomambid/portfolio
      branch: master
      deploy_on_push: false
    dockerfile_path: Dockerfile
    instance_size_slug: basic-xxs
    instance_count: 1
    http_port: 8080
